### ISSUE TITLE
PHP-FPM fallback not enabled

### ISSUE THREAD

**Issue by rawcreative** [zach-adams/hgv-deploy-basic#2]
Even though php-fpm is installed and configured to work as a fallback, it's not actually enabled AS a fallback anywhere, i.e. there is nothing that actually switches to php-fpm when hhvm fails. This is the same for both this repo and the 'Full' repo.

**Comment by zach-adams** [comment]
Whoops, what a silly oversight. Working on it now, in the meantime if you're having issues with hhvm you can change back to php manually by changing the following in your nginx configuration:

```
    location ~ \.php$ {
        fastcgi_buffers 8 256k;
        fastcgi_buffer_size 128k;
        fastcgi_intercept_errors on;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass hhvm;
    }
```

to 

```

    location ~ \.php$ {
        fastcgi_buffers 8 256k;
        fastcgi_buffer_size 128k;
        fastcgi_intercept_errors on;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php;
    }
```

**Comment by zach-adams** [comment]
Newest version should have fallback ready to go!
